#!/usr/bin/env bash

if [[ $# -eq 0 ]]; then
  echo "Algorithm directory name not provided, nothing done."
  exit 1
fi

directory="${1}"

if [[ -e "${directory}" ]]; then
  echo "File $1 already exists, nothing done."
  exit 1
fi

mkdir "${directory}"

cat << 'EOF' > "${directory}/README.md"
# PROBLEM TITLE

## Hints

1. 

## Solutions

### SOLUTION TITLE

```java
```
EOF

echo "1. [LONG TITLE](${directory})" >> README.md
